Mission page upload photo button
PlasticPatrol/PlasticPatrolWeb pull request #346
Opened 2021-04-07 22:47 UTC by alastairdglennie

Added an Upload Pieces button which links directly to the upload new pieces page

![image](https://user-images.githubusercontent.com/9222722/113943916-8a6e4500-97fb-11eb-86a4-f3e738491476.png)

2021-04-07 23:23 UTC, joykuotw commented
Can you rebase the master? thanks.

2021-04-07 23:23 UTC, joykuotw requested changes
Can you rebase the master? thanks.

2021-04-08 14:30 UTC, alastairdglennie commented
> Can you rebase the master? thanks.

Have rebased! 🎉  PTAL

2021-04-08 15:06 UTC, joykuotw approved these changes

2021-04-08 15:07 UTC, merged