Better formatting around mission progress / completion
PlasticPatrol/PlasticPatrolWeb pull request #349
Opened 2021-04-08 00:03 UTC by alastairdglennie

Different example pages:

![image](https://user-images.githubusercontent.com/9222722/113948960-08cfe480-9806-11eb-949f-b2443b217569.png)

![image](https://user-images.githubusercontent.com/9222722/113948983-17b69700-9806-11eb-811d-ae42f472115c.png)
 
![image](https://user-images.githubusercontent.com/9222722/113949000-200ed200-9806-11eb-86ac-11f326dc3f72.png)

2021-04-08 17:17 UTC, joykuotw requested changes
The progress line looks thick in web. might have to tweak the height.

At the second example, 8 day should be plural. Also, shouldn't it be 9 days ago if the end date is 30/03/2021 or I miscalculate?

2021-04-14 20:41 UTC, alastairdglennie commented
> The progress line looks thick in web. might have to tweak the height.
> 
> At the second example, 8 day should be plural. Also, shouldn't it be 9 days ago if the end date is 30/03/2021 or I miscalculate?

Great points, have fixed up now!

2021-04-14 23:29 UTC, joykuotw submitted a review, later dismissed

2021-04-14 23:50 UTC, joykuotw approved these changes

2021-04-14 23:51 UTC, merged