Upgrade to Firebase 9
PlasticPatrol/PlasticPatrolWeb pull request #411
Opened 2021-12-27 15:14 UTC by al1y

Something we should ultimately do because firebase 9 is what's going to be developed going forward (and presumably 8 gets deprecated).

This was initially motivated by discovering that firebase 8 doesn't have local Firebase storage emulation.

Currently this is the minimum effort upgrade which still uses the firebase 8 syntax (they have compatability imports). Current progress and future steps are all here: https://firebase.google.com/docs/web/modular-upgrade.

There's a necessary postinstall patch because capacitor-firebase-auth isn't updated for firebase 9. The capacitor-firebase-auth seems like it hasn't been updated in a while so there might be a newer one we should be using instead but for now this seems like best for min surface area change.

2022-01-04 19:55 UTC, joykuotw requested changes
Any reason we need a patch for `capacitor-firebase-auth`?

The capacitor-firebase-auth 3.0.0 is using Capacitor 3.0.0.

The version of capacitor-firebase-auth we are currently using in the app is based on Capacitor 2 so it would be better to not upgrade this to 3.0.0 or we will have to migrate to Capacitor 3.

We will do the Capacitor migration at some point later as we need to make sure everything is still working.

2022-01-04 21:34 UTC, al1y commented
> Any reason we need a patch for `capacitor-firebase-auth`?
> 
> The capacitor-firebase-auth 3.0.0 is using Capacitor 3.0.0.
> 
> The version of capacitor-firebase-auth we are currently using in the app is based on Capacitor 2 so it would be better to not upgrade this to 3.0.0 or we will have to migrate to Capacitor 3.
> 
> We will do the Capacitor migration at some point later as we need to make sure everything is still working.

Sounds good, just tested it still works after reverting and seems all good 👍 

For context,  I did the upgrade while trying to fix compatability issues that the capacitor-firebase-auth package because it hasn't been upgrade to firebase 8. This resulted in the patch-package I've got set up.

2022-01-05 02:25 UTC, joykuotw commented
> > Any reason we need a patch for `capacitor-firebase-auth`?
> > The capacitor-firebase-auth 3.0.0 is using Capacitor 3.0.0.
> > The version of capacitor-firebase-auth we are currently using in the app is based on Capacitor 2 so it would be better to not upgrade this to 3.0.0 or we will have to migrate to Capacitor 3.
> > We will do the Capacitor migration at some point later as we need to make sure everything is still working.
> 
> Sounds good, just tested it still works after reverting and seems all good 👍
> 
> For context, I did the upgrade while trying to fix compatability issues that the capacitor-firebase-auth package because it hasn't been upgrade to firebase 8. This resulted in the patch-package I've got set up.

Just tested. It works on web but breaks on mobile. It might be related to `react-firebaseui` which we will need to troubleshoot. Otherwise this cannot be merged. I will also have a look when get time.

2022-01-11 00:42 UTC, joykuotw approved these changes

2022-01-11 17:43 UTC, merged